default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: postgres
  password: 123456789
  host: localhost
  port: 5432

  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: blog_test
  username: postgres
  password: 123456789
  host: localhost
  port: 5432

production:
  <<: *default
  database: blog_production
  username: postgres
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>